services:
  - type: web
    name: instagram-clone
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn django_ig.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: django_ig.settings